### ISSUE TITLE
Few VMs show as OFF despite being on

### ISSUE THREAD

**Issue by stomko11** [domalab/ha-unraid#10]
**Describe the bug**
I have 4 VMs running on Unraid (autostart also enabled). After loading this integration, 2 VMs show as off:

**Expected behavior**
I would expect all 4 shown as turned on

**Screenshots**
![image](https://github.com/user-attachments/assets/53d48f73-4e5c-4818-9a02-03f073efa2eb)

![image](https://github.com/user-attachments/assets/02a92cff-ff8e-48db-9afc-c120b1a2f48f)

**Unraid (please complete the following information):**
 - 6.12.13

**Additional context**
Seems to be issue with space and "-" in name of VM
```
2024-10-31 00:16:42.624 ERROR (MainThread) [custom_components.unraid.unraid] Failed to get VM status for Windows 11: error: unexpected data '11'
2024-10-31 00:16:42.664 ERROR (MainThread) [custom_components.unraid.unraid] Failed to get VM status for HA DEV: error: unexpected data 'DEV'

```

**Comment by domalab** [comment]
@stomko11 Thank you very much for providing the info. I'll investigate and implement a fix as soon as soon as possible.

**Comment by mehrwegadresse** [comment]
strange, it seems that only VMs that have a space in their names are affected.

**Comment by domalab** [comment]
@mehrwegadresse @stomko11 I implemented a fix and in my environment its working fine now to detect and control VMs with special characters.

Just testing it with other updates before releasing a new version.

**Comment by domalab** [comment]
@mehrwegadresse @stomko11 I release a new version that addresses the special characters in VM names. Let  me know if it works for you
