### ISSUE TITLE
CPU temp not showing in HA

### ISSUE THREAD

**Issue by marcokreeft87** [domalab/ha-unraid#12]
**Describe the bug**
The CPU temperature is not showing in the integration 

**Screenshots**
![Screenshot_20241104_170830_Chrome](https://github.com/user-attachments/assets/80973cc7-fdd7-4321-ae8c-369cfcaa1f54)
![Screenshot_20241104_170803_Home Assistant](https://github.com/user-attachments/assets/a4191c9c-f0bc-4208-a12e-6c91e2376033)

**Unraid (please complete the following information):**
 - Version 6.12.13

**Comment by domalab** [comment]
@marcokreeft87 Can you please check your Home Assistant log and send me any unraid errors. Could be the code not recognising your type of sensors.

You can also open command prompt on unraid and type in 'sensors' and send me screenshot

**Comment by marcokreeft87** [comment]
All I get in the HA logs about unraid is:

```2024-11-04 02:03:52.237 ERROR (MainThread) [custom_components.unraid.unraid] Error getting cache usage: not enough values to unpack (expected 3, got 0)

2024-11-04 02:03:52.298 ERROR (MainThread) [custom_components.unraid.unraid] UPS info command failed with exit status 1

```

And the console screenshot:

![Screenshot_20241105_062446_Chrome.jpg](https://github.com/user-attachments/assets/56262955-55e1-4722-bcb5-4237f657ee09)

**Comment by domalab** [comment]
@marcokreeft87 thanks for providing the info. I'll look at releasing an update to more broadly detect temp sensor data by next week.

**Comment by marcokreeft87** [comment]
> @marcokreeft87 thanks for providing the info. I'll look at releasing an update to more broadly detect temp sensor data by next week.

Is it possible to add the fan speeds aswel?

**Comment by domalab** [comment]
> > @marcokreeft87 thanks for providing the info. I'll look at releasing an update to more broadly detect temp sensor data by next week.
> 
> Is it possible to add the fan speeds aswel?

I was playing around with detecting fans and fan speeds correctly. Still on my to do list to figure out how to get individual fan speed data captured correctly.

**Comment by domalab** [comment]
@marcokreeft87 I released a new version that should fix cpu and motherboard temp sensor issue. Let me know if it works for you.

**Comment by marcokreeft87** [comment]
Seems to work! Thnx

**Comment by domalab** [comment]
@marcokreeft87 I'm working on the fan sensors and will be released in next update. Just need the integration to detect DC only or PWM or both.

**Comment by domalab** [comment]
Basic fan sensors will be available in next release

![Screenshot 2024-12-23 at 8 40 23 pm](https://github.com/user-attachments/assets/851c852a-cbd6-4575-a3c8-844957eb8216)
