### ISSUE TITLE
Add networking stats

### ISSUE THREAD

**Issue by stplatt** [domalab/ha-unraid#13]
**Is your feature request related to a problem? Please describe.**
I'm missing networking stats from this integration.

**Describe the solution you'd like**
New sensors for inbound and outbound network speeds.

**Additional context**
![image](https://github.com/user-attachments/assets/1aaec905-80bc-4695-9688-06602bcc35dd)

**Comment by domalab** [comment]
@stplatt Thanks for the enhancement request. I'll see if I can add it to next release.

**Comment by domalab** [comment]
@stplatt I updated the code and added inbound and outbound network sensors.

It will also detect if your network interfaces are bonded.

I'll release the update once I'm done testing with other updates.

![Screenshot 2024-11-14 at 4 33 37 pm](https://github.com/user-attachments/assets/96d0654a-1b51-4da8-8d77-1e28dc099546)

![Screenshot 2024-11-14 at 4 34 04 pm](https://github.com/user-attachments/assets/4da95c32-23db-45cf-a962-fc6b9d10d749)

**Comment by domalab** [comment]
@stplatt I release a new version that includes network monitoring sensors. Let me know if it works for you

**Comment by mvanlijden** [comment]
I my environment the status is not correct compared to the Bytes per second in the attributes.
![image](https://github.com/user-attachments/assets/7333eb85-b5b5-4399-984d-dba521a502a5)
![image](https://github.com/user-attachments/assets/fd1f6863-706f-428d-8d88-5975cdc2da99)

**Comment by stplatt** [comment]
Thanks for adding! It seems like something is off in the sensor though. Shouldn't these highlighted numbers be the same?

![image](https://github.com/user-attachments/assets/3df8f5ee-a28f-4f4f-ba46-f955feaaeb52)

**Comment by chilman408** [comment]
Does everyone have this working?  Mine doesn't show any data...

![image](https://github.com/user-attachments/assets/dfd7c9d9-0201-430b-905d-740689297798)

**Comment by chilman408** [comment]
Yes. i am using bonded nics

**Comment by domalab** [comment]
> Yes. i am using bonded nics

Can you please run these commands. Replace bond0 with whatever you called your bonded nic interface.

ifconfig bond0
ip -s link show bond0
ip -s link show

Please provide output

**Comment by ond000** [comment]
> > Yes. i am using bonded nics
> 
> Can you please run these commands. Replace bond0 with whatever you called your bonded nic interface.
> 
> ifconfig bond0 ip -s link show bond0 ip -s link show
> 
> Please provide output

I have same issue at server with bonding so my output:

**ifconfig bond1**
`bond1: flags=5187<UP,BROADCAST,RUNNING,MASTER,MULTICAST>  mtu 9000
        ether 00:60:dd:44:37:62  txqueuelen 1000  (Ethernet)
        RX packets 808425108  bytes 770730866665 (717.7 GiB)
        RX errors 0  dropped 185973  overruns 0  frame 0
        TX packets 144311864  bytes 355853023364 (331.4 GiB)
        TX errors 0  dropped 1 overruns 0  carrier 0  collisions 0`

**ip -s link show bond1**
`10: bond1: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 9000 qdisc noqueue master br1 state UP mode DEFAULT group default qlen 1000
    link/ether 00:60:dd:44:37:62 brd ff:ff:ff:ff:ff:ff
    RX:    bytes   packets errors dropped  missed   mcast           
    770731719960 808429036      0  185979       0       0 
    TX:    bytes   packets errors dropped carrier collsns           
    355853126292 144312808      0       1       0       0 `

**ip -s link show**
`1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    RX:  bytes packets errors dropped  missed   mcast           
     247490817 3018478      0       0       0       0 
    TX:  bytes packets errors dropped carrier collsns           
     247490817 3018478      0       0       0       0 
2: tunl0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
    RX:  bytes packets errors dropped  missed   mcast           
             0       0      0       0       0       0 
    TX:  bytes packets errors dropped carrier collsns           
             0       0      0       0       0       0 
6: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq master br0 state UP mode DEFAULT group default qlen 1000
    link/ether 10:7b:44:16:ba:71 brd ff:ff:ff:ff:ff:ff
    RX:     bytes    packets errors dropped  missed    mcast           
     976740542889 1100289722      0   93008       0 14790329 
    TX:     bytes    packets errors dropped carrier  collsns           
    2162965173994 1816992163      0       0       0        0 
7: eth1: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 9000 qdisc mq master bond1 state UP mode DEFAULT group default qlen 1000
    link/ether 00:60:dd:44:37:62 brd ff:ff:ff:ff:ff:ff
    RX:    bytes   packets errors dropped  missed   mcast           
    471798730138 438547139      0       2       0       0 
    TX:    bytes   packets errors dropped carrier collsns           
    343686157810 136702636      0       0       0       0 
8: eth3: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 9000 qdisc mq master bond1 state UP mode DEFAULT group default qlen 1000
    link/ether 00:60:dd:44:37:62 brd ff:ff:ff:ff:ff:ff permaddr 00:60:dd:44:37:63
    RX:    bytes   packets errors dropped  missed   mcast           
    298933377122 369883699      0       2       0       0 
    TX:    bytes   packets errors dropped carrier collsns           
     12166986880   7610447      0       0       0       0 
9: br0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 10:7b:44:16:ba:71 brd ff:ff:ff:ff:ff:ff
    RX:     bytes    packets errors dropped  missed    mcast           
     950907729191  900248471      0       3       0 14697321 
    TX:     bytes    packets errors dropped carrier  collsns           
    2162966294754 1816996742      0       0       0        0 
10: bond1: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 9000 qdisc noqueue master br1 state UP mode DEFAULT group default qlen 1000
    link/ether 00:60:dd:44:37:62 brd ff:ff:ff:ff:ff:ff
    RX:    bytes   packets errors dropped  missed   mcast           
    770732107260 808430838      0  185981       0       0 
    TX:    bytes   packets errors dropped carrier collsns           
    355853144424 144313080      0       1       0       0 
11: br1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 00:60:dd:44:37:62 brd ff:ff:ff:ff:ff:ff
    RX:    bytes   packets errors dropped  missed    mcast           
    742370978975 484506886      0    7657       0 14416001 
    TX:    bytes   packets errors dropped carrier  collsns           
    355652793467 144115155      0       0       0        0 
12: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN mode DEFAULT group default 
    link/ether 02:42:ea:d9:c8:5d brd ff:ff:ff:ff:ff:ff
    RX:  bytes packets errors dropped  missed   mcast           
             0       0      0       0       0       0 
    TX:  bytes packets errors dropped carrier collsns           
             0       0      0       0       0       0 
13: virbr0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN mode DEFAULT group default qlen 1000
    link/ether 52:54:00:10:48:a8 brd ff:ff:ff:ff:ff:ff
    RX:  bytes packets errors dropped  missed   mcast           
             0       0      0       0       0       0 
    TX:  bytes packets errors dropped carrier collsns           
             0       0      0       0       0       0 `

**Comment by apedance** [comment]
None of my network interfaces shows up. latest version to date.
