### ISSUE TITLE
Add GPU Statistics

### ISSUE THREAD

**Issue by martindell** [domalab/ha-unraid#16]
First off - thank you for this addon.  I'm using it to halt a GPU-heavy Unraid docker to save my home battery from running out of juice 👍 

**Is your feature request related to a problem? Please describe.**
I use the GPU Statistics plugin to display this kind of info on my Unraid dashboard.

![Screenshot 2024-11-17 at 09 34 21](https://github.com/user-attachments/assets/f9f91951-d529-426d-a13f-7f5205968dc0)

**Describe the solution you'd like**
It'd be great to see this kind of info as sensors inside the HomeAssistant addon

**Additional context**
I can pull some of this GPU info via user scripts. Maybe there's a way to pass it back to the HomeAssistant addon?

**Comment by domalab** [comment]
@martindell can you run this commands from unraid console?

To retrieve GPU information (NVIDIA, AMD, and integrated GPUs) on an Unraid system and save it to a text file, you can use the following approaches:

1. Using lspci

The lspci command can be used to list all PCI devices, including GPUs. You can filter the output for NVIDIA, AMD, and integrated GPUs.

lspci | grep -i 'vga\|3d\|display' > /boot/config/gpu_info.txt

	•	Explanation:
	•	grep -i 'vga\|3d\|display': Filters lines related to GPUs.
	•	> /boot/config/gpu_info.txt: Redirects output to a file.

2. Using nvidia-smi for NVIDIA GPUs

If you have the NVIDIA driver plugin installed, nvidia-smi provides detailed information for NVIDIA GPUs.

nvidia-smi -q > /boot/config/nvidia_gpu_info.txt

	•	Explanation:
	•	-q: Outputs detailed GPU information.
	•	> /boot/config/nvidia_gpu_info.txt: Saves the output to a file.

3. Using glxinfo for Integrated and AMD GPUs

If you have mesa-utils installed, you can use glxinfo to retrieve GPU details.

glxinfo | grep -i 'device\|renderer' > /boot/config/gpu_info_glx.txt

4. Using inxi for Comprehensive GPU Info

If you have inxi installed, it provides detailed GPU information.

inxi -Gxx > /boot/config/gpu_info_inxi.txt

Installing Missing Tools

If some commands are missing, you might need to install additional packages using nerdpack or Unraid plugins. For example:
	•	nvidia-smi requires the NVIDIA driver plugin.
	•	glxinfo and inxi might need nerdpack.

**Comment by domalab** [comment]
@martindell Would you mind testing experimental gpu monitoring feature?

If you can, then I'll upload the code and let you know how to test it.

**Comment by martindell** [comment]
Sure, I'd be delighted to 👍

**Comment by s1mpleman** [comment]
> @martindell Would you mind testing experimental gpu monitoring feature?
> 
> If you can, then I'll upload the code and let you know how to test it.

Happy to test as well, just came here to make the same feature request.

**Comment by ich777** [comment]
Just as a heads up @domalab if you call the the vendor utilities too often in a short period of time this can cause high CPU utilization and therefore higher power draw.

**Comment by domalab** [comment]
Thanks for the heads up. That is good to know. Appreciate it

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by domalab** [comment]
Decided due to the complexity and me being limited to only an intel gpu that I wont be progressing further with this. Maybe someone else can look into adding this feature.
