### ISSUE TITLE
Add docker containers stats

### ISSUE THREAD

**Issue by marcokreeft87** [domalab/ha-unraid#17]
Can you please add information about the docker containers running in Unraid?
Like state, name ofcourse, CPU usage and such.

No rush :)

PS. My end goal is make a dashboard like this with your integration:

https://github.com/EvisHome/Home-Assistant/tree/main/dashboards%2Funraid

**Comment by domalab** [comment]
@marcokreeft87 I think I'll create a seperate docker monitoring module that pulls these metrics and have it as an option in the integration setup / configuration. Just in case no one else wants to see this type of metrics and extra sensors.

      - version
      - containers_running
      - containers_paused
      - containers_stopped
      - containers_cpu_percentage
      - containers_memory_percentage
      - cpu_percentage
      - health
      - uptime
      - memory
      - memory_percentage
      - network_speed_up
      - network_speed_down

**Comment by marcokreeft87** [comment]
Sounds perfect

**Comment by domalab** [comment]
@marcokreeft87 I created a docker insights module for the integration. 

The following sensors gets created

1. Container CPU Usage
2. Container Memory Usage
3. Container Network Download / Upload
4. Total Containers 
5. Running Containers
6. Paused Containers

Feel free to checkout the experimental feature and let me know what you think

You will need to copy the unraid folder from experiment/docker-insights branch to your home assistant instance.

You can only enable docker insights after the initial configuration setup and it takes about a minute to initialise and create the sensors.

![Screenshot 2024-11-24 at 4 53 54 pm](https://github.com/user-attachments/assets/e581fa08-5c77-404f-a701-9222392d0440)

You will see 2 device entries after initialisation 

![Screenshot 2024-11-24 at 4 55 05 pm](https://github.com/user-attachments/assets/6a30146e-57a5-4c07-af9a-82d8a09ed8fc)

I'll look if its possible to get docker uptime data

**Comment by marcokreeft87** [comment]
Just installed it. But first issue I see is I have all new entities now for the old values:

![image](https://github.com/user-attachments/assets/6ad76ff0-2048-4633-8a7f-8e24515008ba)

And some are not working anymore:

![image](https://github.com/user-attachments/assets/4a20c262-454a-471c-9108-a3922db4de9a)

**Comment by domalab** [comment]
> Just installed it. But first issue I see is I have all new entities now for the old values:
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/6ad76ff0-2048-4633-8a7f-8e24515008ba)
> 
> 
> 
> And some are not working anymore:
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/4a20c262-454a-471c-9108-a3922db4de9a)
> 
> 

I made updates to the code to fix a unique ID issue with sensors and it also now gets the unraid hostname to use with naming convention of sensors. This allows you to add multiple unraid servers without issues. 

Unfortunately the update doesn't migrate existing entities to new ones. 

Best is to remove the integration and start fresh. Sorry about that

**Comment by marcokreeft87** [comment]
> the integration and st

No worries :)

**Comment by marcokreeft87** [comment]
If you add the integration the docker checkbox isnt there

**Comment by marcokreeft87** [comment]
Made a little dashboard with the new sensors :) 
![image](https://github.com/user-attachments/assets/863c104a-1d1c-40a7-a4b9-933538e9aa6f)

**Comment by domalab** [comment]
I updated the sensors to look like this. 1 sensor per container with attributes.

![Screenshot 2024-11-26 at 5 26 02 pm](https://github.com/user-attachments/assets/e5ea20f4-186c-48ca-ba35-ff721eb30749)

I updated the code to use dockersocket container as it provides better results so you need to have dockersocket container running on unraid.
![Screenshot 2024-11-26 at 5 29 51 pm](https://github.com/user-attachments/assets/6ada75ce-da66-484d-baa7-c467a2c90f54)

**Comment by marcokreeft87** [comment]
Im trying the latest version right now. The CPU temp was my fault btw :)

**Comment by marcokreeft87** [comment]
Do I need special settings for dockersocket? 
![image](https://github.com/user-attachments/assets/1be737a0-8de4-4c6a-b031-1703d9681371)
Its not working currently 

![image](https://github.com/user-attachments/assets/2e9b51ed-1863-4b19-9e26-da8f6a6c6964)

**Comment by domalab** [comment]
> Do I need special settings for dockersocket? 
> 
> ![image](https://github.com/user-attachments/assets/1be737a0-8de4-4c6a-b031-1703d9681371)
> 
> Its not working currently 
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/2e9b51ed-1863-4b19-9e26-da8f6a6c6964)
> 
> 

Change your network from bridge to host.

**Comment by marcokreeft87** [comment]
Oh stupid me. That coming from a guy that works with docker daily xD Thnx it's working now

**Comment by domalab** [comment]
> Oh stupid me. That coming from a guy that works with docker daily xD Thnx it's working now

You can monitor the logs in dockersocker for activity.

**Comment by domalab** [comment]
I have resolved this now and docker insights feature will be available in next update. Pre-reqs will be to have dockersocket proxy container running on unraid.

I have also added fixes that it will load and unload faster without holding HA back from starting / restarting

**Comment by domalab** [comment]
I have decided to remove this Frankenstein of a feature as its causing too many stability issues and sleepless nights.

This integration achieves the same but has more options if someone wants have detailed container metrics.

[https://github.com/ualex73/monitor_docker](url)

**Comment by marcokreeft87** [comment]
But in the latest release the docker feature is working right?

**Comment by twistedsanity** [comment]
> https://github.com/ualex73/monitor_docker

Thanks for the 'frank' response and suggestion, I was having a nightmare with running out of sessions due to the number of queries being spawned (large unraid docker setup) thanks again. I think it is sensible to keep docker integration separate, if for only troubleshooting advantages.
