### ISSUE TITLE
UPS info command failed

### ISSUE THREAD

**Issue by tjorim** [domalab/ha-unraid#2]
Getting this error and sensor state is Unknown.
I think we should mark this entity as `unavailable` instead.
```
This error originated from a custom integration.

Logger: custom_components.unraid.unraid
Source: custom_components/unraid/unraid.py:274
integration: UNRAID (documentation, issues)
First occurred: 10:00:38 (2 occurrences)
Last logged: 10:01:27

UPS info command failed
```

**Comment by domalab** [comment]
So you don't have UPS attached to your UNRAID server? 

I can look at implementing an option to check for UPS. If connected then create sensor, if not connected do nothing.

**Comment by tjorim** [comment]
Indeed I don't. I disabled the sensor entity but still getting the error. I think the update function should not be called when it's disabled.

**Comment by domalab** [comment]
Thanks for letting me know. I'll look into it

**Comment by domalab** [comment]
@tjorim I added an option to specify if you have a UPS connected or not to your server. I have tested it on my server and it's working. You also have the option now to later add enable the UPS option if you do get one.

**Comment by Ninja-FSE** [comment]
`Logger: custom_components.unraid.unraid
Källa: custom_components/unraid/unraid.py:343
integration: UNRAID ([dokumentation](https://github.com/domalab/ha-unraid/wiki), [ärenden](https://github.com/domalab/ha-unraid/issues))
Inträffade först: 17:49:43 (3 händelser)
Senast loggade: 17:59:51
UPS info command failed with exit status 1`

Running the latest version of Unraid (6.12.13) and Home assistant

` Core 2024.10.2
Supervisor 2024.10.3
Operating System 13.1
Frontend 20241002.3`

Unraid Home assistant Integration version is 0.1.5

Cat get rid of this error message, i dont have a UPS attached so i have not marked the UPS checkbox. have tryed to mark it, save, and then remove the checkmark, save again, restart HA, still getting the error message

**Comment by domalab** [comment]
@Ninja-FSE what happens if you disable the ups sensor entity? Still generating warnings?

**Comment by Ninja-FSE** [comment]
Sorry for late reply, i disabled the sensor and im still getting the error im affraid.

**Comment by Ninja-FSE** [comment]
Just bumping the thread to see if you have looked into this yet?

**Comment by domalab** [comment]
@Ninja-FSE I haven't forgotten about this. I implemented a fix by disabling automatic detection of the UPS. I'm leaving it now to manual setup. Just doing a bit of testing with other updates before releasing it.

**Comment by domalab** [comment]
@Ninja-FSE @tjorim I released a new version that should fix your issue. UPS auto detection is removed and UPS sensor now gracefully handles unraid instances without UPS connected. You might need to re-install the integration and clear browser cache for it to work.

**Comment by domalab** [comment]
> > @Ninja-FSE @tjorim I released a new version that should fix your issue. UPS auto detection is removed and UPS sensor now gracefully handles unraid instances without UPS connected. You might need to re-install the integration and clear browser cache for it to work.
> 
> Sweet thanks, gonna try this tomorrow!

I tested it on 2 unraid systems. One with UPS and other without. Worked for me but let me know how you go.
