### ISSUE TITLE
Unraid syslog shows lots of subsequent start/close SSH session messages at the polling time

### ISSUE THREAD

**Issue by jmot205** [domalab/ha-unraid#20]
**Describe the bug**
When the HA integration polls for the Unraid stats it seems to do it with heaps of subsequent session activities, which floods the Unraid syslog with all the session start/stop logs, making it hard to see anything else. Is the integration potentially polling each Unraid stat individually and causing all the start/stop messages? The sshd session seems to be the same number, so presumably it isn't just opening and closing a new SSH session for each parameter. 

**Expected behavior**
A single SSH connect and disconnect log in the Unraid syslog per polling time. 

**Screenshots**
![Screenshot_20241124_110838_Firefox](https://github.com/user-attachments/assets/04146bf9-1226-4477-bd2a-b350cc4d9375)

**Unraid (please complete the following information):**
 - Version 6.12.13

**Comment by domalab** [comment]
@jmot205 Thanks for reporting this. I'll see if I can make some improvements.

**Comment by domalab** [comment]
I have resolved this and will be included in next update.

**Comment by jmot205** [comment]
Legend, thanks 👍

**Comment by domalab** [comment]
@jmot205 Even though the integration shows a lot less ssh connection in the logs, it will still log ssh connections depending on how frequently the sensors update. To get around this I have written a script to suppress the ssh logs from HA.

https://github.com/domalab/ha-unraid/wiki/Troubleshooting#ssh-session-log-spam
