### ISSUE TITLE
"read only" user for HA on my unraid server?

### ISSUE THREAD

**Issue by RezzZ** [domalab/ha-unraid#21]
**Is your feature request related to a problem? Please describe.**
The readme suggests we use the root username and password. I find that extremely risky giving my HA docker container full access over my unraid server. I much rather have a "read only" user that HA uses so that HA can warn me about things.

**Describe the solution you'd like**
I would like to see a suggestion in the readme on this intergration port how to setup this user, what rights does it require etc.

**Comment by domalab** [comment]
@RezzZ Thanks for the feature request. The reason why it requires root access is because it connects over SSH to Unraid to execute commands for retrieving data for sensors and control docker and vms. I'm not aware of least access privilege user accounts you can configure from Unraid UI. 

Unraid is primarily designed for simplicity, often requiring root access for many operations, including SSH and WebUI access.

**Comment by RezzZ** [comment]
Ahh okay that makes sense. Thanks for the explanation! I already installed it and it works great. I primarily installed it due to a power outage last night and I wasn't aware of this so now I set up a CRITICAL (repeating) HA alert when the power is down / apc is offline. Works like a charm :)

**Comment by aminhusni** [comment]
> @RezzZ Thanks for the feature request. The reason why it requires root access is because it connects over SSH to Unraid to execute commands for retrieving data for sensors and control docker and vms. I'm not aware of least access privilege user accounts you can configure from Unraid UI. 
> 
> Unraid is primarily designed for simplicity, often requiring root access for many operations, including SSH and WebUI access.

Perhaps this can be revisited later. 
Think I'll gather some information first, see the command lists and such. 

One idea I have is to connect to Unraid with root for only the initial setup which will then create a user in Unraid SSH with lesser access. 
After that, root access credentials are removed and if there is any additional permissions to be granted, can simply ask for root login again? 🤔

Allowing full SSH root access credentials just sitting in Home Assistant seems a bit too risky, considering UNRAID is used to store very important data generally.
