### ISSUE TITLE
HACS/Repo not working

### ISSUE THREAD

**Issue by hawaaiianmiraclecreel** [domalab/ha-unraid#22]
Having the same issue as https://github.com/domalab/ha-unraid/issues/8

![image](https://github.com/user-attachments/assets/d6386fa4-0cbd-4660-b570-8df80889327f)
![image](https://github.com/user-attachments/assets/f02db97c-7d3a-41da-85ab-399607ce2646)

**Comment by domalab** [comment]
@hawaaiianmiraclecreel Are you trying to add this HACS integration as a HA Add-On repository?

It will only work under HACS and looks like this

![Screenshot 2024-12-02 at 5 08 20 pm](https://github.com/user-attachments/assets/63221774-6548-4c4d-a745-65158617cd4e)

And the link ads the custom repository in HACS like this

![Screenshot 2024-12-02 at 5 10 20 pm](https://github.com/user-attachments/assets/a0989ce8-58d2-4f05-9b1b-b9923ca3f0b4)

**Comment by hawaaiianmiraclecreel** [comment]
OOf you are totally right, I did not realize HACS was seperate from the add on store! I apologize
