### ISSUE TITLE
Add HASS Unraid entities for system status, alerts, parity checks, updates, and drive metrics

### ISSUE THREAD

**Issue by Guruleenyc** [domalab/ha-unraid#25]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
It would be awesome to have HASS Unraid entities for:

- array status (parity check, data rebuild, etc.)
- notifications for alerts, warnings
- last parity check and result
- plugin updates
- interface speeds (snmp?)
- drive temp for array and cache drives

**Use Case or Why Do You Want This?**
Describe a specific scenario where this feature would be helpful or explain why you think it's necessary.

**Priority of Request**
How important is this feature to you?  
- \[ ] High
- \[ ] Medium
- \[x] Low

**Additional context**
N/a

**Comment by domalab** [comment]
@Guruleenyc 

The following is in next release

[x] Drive temp for array and cache drives
[x] Interface Speeds: NICs show Inbound and Outbound traffic with details in attributes (Link Speed, Duplex Mode, etc)

The others will be available one day :)

**Comment by domalab** [comment]
[x] Array Status: Parity Check Status sensor added with attributes.
