### ISSUE TITLE
Access to HA if on the same machine

### ISSUE THREAD

**Issue by dsfsdbvxc** [domalab/ha-unraid#26]
**Describe the bug**
When trying to set up the integration, I'm getting the error  message 'Failed to connect to Unraid server'

HA is running on the unraid server, I've tried accessing with:
192.168.1.8 (Unraid servers IP address)
http://192.168.1.8
unraid-server (its host name)

Confirmed ssh is enabled and server is accessible using both IP address and host name.
Tried accessing Unraid server from HA using ssh and the terminal addon, but get 'Connection refused'.
Can ping the server ok though.

HA is running on the Unraid server as a VM using HASSIO. It has its own IP address, not sharing the hosts. 

**Expected behavior**
Integration connects to the Unraid server via ssh

**Screenshots**
n/a

**Unraid (please complete the following information):**
 - Version 6.12.13 and 6.12.14

**Additional context**
Not sure if its something I'm doing wrong, or an issue with connecting to the Unraid server when HA is running on the same machine

**Comment by domalab** [comment]
> **Describe the bug**
> 
> When trying to set up the integration, I'm getting the error  message 'Failed to connect to Unraid server'
> 
> 
> 
> HA is running on the unraid server, I've tried accessing with:
> 
> 192.168.1.8 (Unraid servers IP address)
> 
> http://192.168.1.8
> 
> unraid-server (its host name)
> 
> 
> 
> Confirmed ssh is enabled and server is accessible using both IP address and host name.
> 
> Tried accessing Unraid server from HA using ssh and the terminal addon, but get 'Connection refused'.
> 
> Can ping the server ok though.
> 
> 
> 
> HA is running on the Unraid server as a VM using HASSIO. It has its own IP address, not sharing the hosts. 
> 
> 
> 
> **Expected behavior**
> 
> Integration connects to the Unraid server via ssh
> 
> 
> 
> **Screenshots**
> 
> n/a
> 
> 
> 
> **Unraid (please complete the following information):**
> 
>  - Version 6.12.13 and 6.12.14
> 
> 
> 
> **Additional context**
> 
> Not sure if its something I'm doing wrong, or an issue with connecting to the Unraid server when HA is running on the same machine
> 
> 

Have you tried to use the SSH web terminal HA add-on to test ssh from HASOS to unraid?

Is your HA VM on the same network as Unraid with also a 192.168.1.x address?

Do you use VLANs for HA VM?

Any firewalls in between HA VM and Unraid?

**Comment by dsfsdbvxc** [comment]
Apologies, working now.

Weird, had to disable ssh on my server and re-enable

**Comment by dsfsdbvxc** [comment]
Closed
