### ISSUE TITLE
After last HA update, unRAID integration don't work

### ISSUE THREAD

**Issue by PrzemekSkw** [domalab/ha-unraid#27]
**Describe the bug**
I have HA core in docker on unRAID.
Last update 2024.12.0 broke unRAID integreation. I install it with HACS.

**Expected behavior**
Work like before

**HA Log**
```
Rejestrator: homeassistant.config_entries
Źródło: config_entries.py:640
Pierwsze zdarzenie: 10:25:07 (1 zdarzenia)
Ostatnio zalogowany: 10:25:07

Error setting up entry Unraid Server (192.168.0.208) for unraid
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/unraid/__init__.py", line 61, in async_setup_entry
    await coordinator.async_config_entry_first_refresh()
  File "/usr/local/lib/python3.13/site-packages/homeassistant/helpers/update_coordinator.py", line 306, in async_config_entry_first_refresh
    await self._async_refresh(
        log_failures=False, raise_on_auth_failed=True, raise_on_entry_error=True
    )
  File "/usr/local/lib/python3.13/site-packages/homeassistant/helpers/update_coordinator.py", line 379, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/unraid/coordinator.py", line 232, in _async_update_data
    system_stats = await self._async_update_disk_data(system_stats)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/unraid/coordinator.py", line 151, in _async_update_disk_data
    disk_data = await self.api.get_individual_disk_usage()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/unraid/unraid.py", line 309, in get_individual_disk_usage
    disk_info = await self.get_disk_info()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/unraid/unraid.py", line 202, in get_disk_info
    temp_result = await self.execute_command(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<8 lines>...
    )
    ^
  File "/config/custom_components/unraid/unraid.py", line 104, in execute_command
    result = await self.conn.run(command)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/asyncssh/connection.py", line 4515, in run
    return await process.wait(check, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/asyncssh/process.py", line 1562, in wait
    await asyncio.wait_for(self.communicate(), timeout)
  File "/usr/local/lib/python3.13/asyncio/tasks.py", line 507, in wait_for
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/asyncssh/process.py", line 1451, in communicate
    await self.wait_closed()
  File "/usr/local/lib/python3.13/site-packages/asyncssh/process.py", line 1208, in wait_closed
    await self._chan.wait_closed()
  File "/usr/local/lib/python3.13/site-packages/asyncssh/channel.py", line 795, in wait_closed
    await self._close_event.wait()
  File "/usr/local/lib/python3.13/asyncio/locks.py", line 213, in wait
    await fut
asyncio.exceptions.CancelledError: Global task timeout
```

**Unraid (please complete the following information):**
 - Version 6.12.14

**Additional context**
Integration version - 2024.11.15

**Comment by domalab** [comment]
> **Describe the bug**
> 
> I have HA core in December Coker on unRAID.
> 
> Last update 2024.12.0 broke unRAID integreation. I install it with HACS.
> 
> 
> 
> **Expected behavior**
> 
> Work like before
> 
> 
> 
> **HA Log**
> 
> ```
> 
> Rejestrator: homeassistant.config_entries
> 
> Źródło: config_entries.py:640
> 
> Pierwsze zdarzenie: 10:25:07 (1 zdarzenia)
> 
> Ostatnio zalogowany: 10:25:07
> 
> 
> 
> Error setting up entry Unraid Server (192.168.0.208) for unraid
> 
> Traceback (most recent call last):
> 
>   File "/usr/local/lib/python3.13/site-packages/homeassistant/config_entries.py", line 640, in __async_setup_with_context
> 
>     result = await component.async_setup_entry(hass, self)
> 
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/config/custom_components/unraid/__init__.py", line 61, in async_setup_entry
> 
>     await coordinator.async_config_entry_first_refresh()
> 
>   File "/usr/local/lib/python3.13/site-packages/homeassistant/helpers/update_coordinator.py", line 306, in async_config_entry_first_refresh
> 
>     await self._async_refresh(
> 
>         log_failures=False, raise_on_auth_failed=True, raise_on_entry_error=True
> 
>     )
> 
>   File "/usr/local/lib/python3.13/site-packages/homeassistant/helpers/update_coordinator.py", line 379, in _async_refresh
> 
>     self.data = await self._async_update_data()
> 
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/config/custom_components/unraid/coordinator.py", line 232, in _async_update_data
> 
>     system_stats = await self._async_update_disk_data(system_stats)
> 
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/config/custom_components/unraid/coordinator.py", line 151, in _async_update_disk_data
> 
>     disk_data = await self.api.get_individual_disk_usage()
> 
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/config/custom_components/unraid/unraid.py", line 309, in get_individual_disk_usage
> 
>     disk_info = await self.get_disk_info()
> 
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/config/custom_components/unraid/unraid.py", line 202, in get_disk_info
> 
>     temp_result = await self.execute_command(
> 
>                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>     ...<8 lines>...
> 
>     )
> 
>     ^
> 
>   File "/config/custom_components/unraid/unraid.py", line 104, in execute_command
> 
>     result = await self.conn.run(command)
> 
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/local/lib/python3.13/site-packages/asyncssh/connection.py", line 4515, in run
> 
>     return await process.wait(check, timeout)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/local/lib/python3.13/site-packages/asyncssh/process.py", line 1562, in wait
> 
>     await asyncio.wait_for(self.communicate(), timeout)
> 
>   File "/usr/local/lib/python3.13/asyncio/tasks.py", line 507, in wait_for
> 
>     return await fut
> 
>            ^^^^^^^^^
> 
>   File "/usr/local/lib/python3.13/site-packages/asyncssh/process.py", line 1451, in communicate
> 
>     await self.wait_closed()
> 
>   File "/usr/local/lib/python3.13/site-packages/asyncssh/process.py", line 1208, in wait_closed
> 
>     await self._chan.wait_closed()
> 
>   File "/usr/local/lib/python3.13/site-packages/asyncssh/channel.py", line 795, in wait_closed
> 
>     await self._close_event.wait()
> 
>   File "/usr/local/lib/python3.13/asyncio/locks.py", line 213, in wait
> 
>     await fut
> 
> asyncio.exceptions.CancelledError: Global task timeout
> 
> ```
> 
> 
> 
> **Unraid (please complete the following information):**
> 
>  - Version 6.12.14
> 
> 
> 
> **Additional context**
> 
> Integration version - 2024.11.15
> 
> 

Thanks. I'm aware of this and will be releasing an update this weekend
