### ISSUE TITLE
Missing custom pool device

### ISSUE THREAD

**Issue by ond000** [domalab/ha-unraid#31]
**Is your feature request related to a problem? Please describe.**
I miss entity for disk usage for custom pool disk, I can see Cache pool disk in HA, but I can't see another pool disk which I have created. Regarding disk usage I see Array, Boot, Cache, Docker vDisk, Log Filesystem, and 10 disks which are part of Array, but I have another pool disk named "temp", which is not populated to HA.

**Describe the solution you'd like**
In HA I should see disk usage for all pool disks, not only for Cache

**Use Case or Why Do You Want This?**
Describe a specific scenario where this feature would be helpful or explain why you think it's necessary.
I would like to monitor custom pool disks

**Priority of Request**
How important is this feature to you?  
- \[ ] High
- \[x] Medium
- \[ ] Low

**Additional context**

**Unraid (please complete the following information):**
 - Version 6.12.13

**Comment by domalab** [comment]
I haven't gotten around to extend the code yet to include custom pool devices.

**Comment by domalab** [comment]
This has been addressed and will be available in the next release
