### ISSUE TITLE
Error getting array usage: division by zero

### ISSUE THREAD

**Issue by maxbec** [domalab/ha-unraid#32]
**Describe the bug**
Error getting array usage: division by zero

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/c2620459-4b31-4899-89aa-8d89140b7416)

**Unraid (please complete the following information):**
 - 7.0.0 RC1

**Home Assistant (please complete the following information):**
![image](https://github.com/user-attachments/assets/72d792a8-900a-4340-a907-ae3c26fd79be)

**Home Assistant installation type (please complete the following information):**
- \[ ] Docker / Container  
- \[x] Virtual Machine
- \[ ] Raspberry Pi

**Priority of Request**
- \[ ] High  
- \[x] Medium  
- \[ ] Low

**Comment by domalab** [comment]
This has been addressed and will be available in the next release
