### ISSUE TITLE
Power Consumption Monitoring

### ISSUE THREAD

**Issue by domalab** [domalab/ha-unraid#4]
**Is your feature request related to a problem? Please describe.**
Currently, the Unraid integration can detect and show basic UPS status information, but does not provide power consumption metrics that could be used in the Energy Dashboard. This misses the opportunity to track and visualize UPS power usage alongside other devices in Home Assistant.

**Describe the solution you'd like**
Add power consumption monitoring for APC Smart-UPS devices connected to Unraid servers. Specifically:
- Current power consumption (Watts)
- Energy consumption (kWh)
- Load percentage
These metrics should be compatible with Home Assistant's Energy Dashboard for tracking and visualization.

**Additional context**
The Unraid integration already detects UPS presence and pulls basic metrics using apcaccess. This feature would extend the existing UPS monitoring to include power-specific sensors with proper device classes (SensorDeviceClass.POWER and SensorDeviceClass.ENERGY) for Energy Dashboard integration.

**Comment by domalab** [comment]
Updated code to create 3 sensors to track UPS power and load

![Screenshot 2024-11-13 at 11 52 44 am](https://github.com/user-attachments/assets/b2c15021-bd15-40c8-bb5a-20cd3dcb8c69)
![Screenshot 2024-11-13 at 11 53 01 am](https://github.com/user-attachments/assets/4be0e4e9-1739-445d-8107-6d4713586abe)
![Screenshot 2024-11-13 at 11 56 17 am](https://github.com/user-attachments/assets/8fcf520c-1a7e-4316-a4c3-e9fa0c0f257c)

**Comment by Guruleenyc** [comment]
AWESOME! Thank you for the great work. I'll check it out.

**Comment by Guruleenyc** [comment]
My HA integration is still at version 0.1.5, how do I upgrade to your new code to take advantage of new features?

**Comment by domalab** [comment]
@Guruleenyc I will release the new version this weekend.

**Comment by domalab** [comment]
@Guruleenyc I release a new version which creates power consumption sensors. Let me know if it works for you

**Comment by Guruleenyc** [comment]
How do I upgrade?

**Comment by martindell** [comment]
> How do I upgrade?

in HACS, click the three dots and then 'update information'
![Screenshot 2024-11-17 at 09 54 17](https://github.com/user-attachments/assets/fb24ab3f-aabb-4b57-b0e7-389018ce7246)

**Comment by domalab** [comment]
Have you tried Update Information or Redownload to pull new version?

You can also try to clear web and HA mobile app cache as it sometimes holds onto old home assistant data.

You can also delete __pycache__ folder from \config\custom_components\unraid to see if it resolves the issue.

**Comment by Guruleenyc** [comment]
I'm not getting any energy consumption data, just line voltage... ![Screenshot_20241118-062325.png](https://github.com/user-attachments/assets/8229fd02-e134-4de2-b2b4-3329d8cd1a41)

**Comment by domalab** [comment]
@Guruleenyc Is this still an issue for you?

**Comment by Guruleenyc** [comment]
> @Guruleenyc Is this still an issue for you?

Yes still an issue. ![Screenshot_20241123-070249.png](https://github.com/user-attachments/assets/f9b0ba33-2761-4837-95e8-30d958cb4b85)

**Comment by domalab** [comment]
@Guruleenyc I found the issue. The UPS Sensor is looking for the NOMPOWER attribute which your UPS model doesn't appear to have. 

I might have a fix but you will need to test it please by copying the unraid folder to your HA instance custom_components folder.
