### ISSUE TITLE
No new device called Unraid Docker

### ISSUE THREAD

**Issue by tjorim** [domalab/ha-unraid#41]
**Describe the bug**
I was just checking out the wiki (I did not find it at first as I was only looking at the readme) and managed to enable the Docker Insights Beta feature. The documentation says "Once enabled the docker insights will initialise and depending on your system and network takes about a minute to create a new device called Unraid Docker. This contains all the diagnostic entities for the containers." However, I only see 1 device with xx entities.

**Expected behavior**
While it (the unraid server) is only 1 physical device, it would make sense to me seeing things grouped in devices as the wiki article implied to have a better overview. Now I have 1 with a long list of 80+ entities.

**Screenshots**

**Unraid (please complete the following information):**
 - Version 7.0.0-rc.2

**Home Assistant (please complete the following information):**
 - Version 2025.1.0b3

**Home Assistant installation type (please complete the following information):**
Home Assistant OS
- \[ ] Docker / Container  
- \[ ] Virtual Machine
- \[ ] Raspberry Pi

**Priority of Request**
- \[ ] High  
- \[ ] Medium  
- \[ ] Low  

**Additional context**

**Comment by domalab** [comment]
I have decided to remove this Frankenstein of a feature as its causing too many stability issues and sleepless nights.

This integration achieves the same but has more options if someone wants have detailed container metrics.

[https://github.com/ualex73/monitor_docker](url)

**Comment by artifactdev** [comment]
Thats sad. It worked before the latest update just fine and i wwas able to start and stop containers just fine. Only the latest update broke it and monitor_docker doesn't support ssh login.

**Comment by tjorim** [comment]
Docker is still implemented and working, only the new insights are removed.

**Comment by domalab** [comment]
Yes correct! Docker Insights(Beta) has got nothing to do with controlling containers (stop/start). It only provides detailed metrics on running containers (CPU, Memory, Network, Image, Version)

Controlling VMs/Containers is part of the base unraid integration code and located in switches.py file. It communicates to unraid via SSH and uses virsh and docker commands.

We're the Docker Insights plugin / feature don't use SSH and relies on dockersocket container and communicates over http to retrieve container metrics.
