### ISSUE TITLE
Failing to set up with Docker Insights enabled

### ISSUE THREAD

**Issue by CZonin** [domalab/ha-unraid#42]
**Describe the bug**
When enabling Docker Insights, the integration fails to set up. I've tried removing and re-adding it, but it still fails. Dockersocket container is installed in my Unraid system.

**Expected behavior**
Integration will set up properly with Docker Insights enabled and Dockersocket installed.

**Unraid (please complete the following information):**
 - Version 6.12.14

**Home Assistant (please complete the following information):**
 - Version 2024.12.5

**Home Assistant installation type (please complete the following information):**
- \[x] Docker / Container  
- \[ ] Virtual Machine
- \[ ] Raspberry Pi

**Priority of Request**
- \[ ] High  
- \[x] Medium  
- \[ ] Low  

**Additional context**
Is there any additional configuration that needs to be done with Dockersocket?

**Comment by domalab** [comment]
Feature removed in next version due to causing stability issues with HA and other users
