### ISSUE TITLE
Update Interval and Unraid Drive Spin-down 

### ISSUE THREAD

**Issue by Guruleenyc** [domalab/ha-unraid#7]
I noticed that my unraid array drives were no longer spinning down after implementing this integration with homeassistant. 

Can we increase the maximum update interval from one hour to at least 12 hours in (43200 sec) ? 

This will allow unraid customers to have their Drive spin down without the need for near real time status updates and home assistant.

**Comment by domalab** [comment]
@Guruleenyc would you mind testing it out by updating the following files.

```python
# const.py
DEFAULT_CHECK_INTERVAL = 3600  # increase default to 1 hour
MAX_CHECK_INTERVAL = 43200  # allow up to 12 hours

# config_flow.py
vol.Optional(CONF_CHECK_INTERVAL, default=DEFAULT_CHECK_INTERVAL): vol.All(
    int, vol.Range(min=300, max=MAX_CHECK_INTERVAL)  # increase max, set min to 5 minutes
),
```

Will be good to know if it makes a difference or not

**Comment by Guruleenyc** [comment]
I modified the two files and then reloaded the Unraid integration in HA. It's still not picking up the new Max and still States 3600 as being the limit. Do I have to restart HA as well?

**Comment by domalab** [comment]
@Guruleenyc thanks for checking. Working on a solution; will update soon.

**Comment by Guruleenyc** [comment]
Any update, or can I help test for you?

**Comment by domalab** [comment]
@Guruleenyc 

Thank you for checking in! I’m currently traveling and won’t be able to update the code until mid-November. Once I’m back, I’ll prioritize reviewing and implementing any necessary changes. Appreciate your patience!

**Comment by Guruleenyc** [comment]
@domalab, Any update or advice?

**Comment by mvanlijden** [comment]
Also see the same behavior, hope you can update this month.
Hope the new delayed update interval will only apply to disk updates, as I would like faster updates on other components that are not affected by disks which are spinned up.

**Comment by domalab** [comment]
@Guruleenyc @mvanlijden I'll be back on deck next week and expect an update by mid November 😊

**Comment by Guruleenyc** [comment]
> @Guruleenyc @mvanlijden I'll be back on deck next week and expect an update by mid November 😊

Awesome! Thank you.

**Comment by domalab** [comment]
@Guruleenyc @mvanlijden I have updated the code and still testing it internally but this is what I had in mind for the update intervals for Disks and other sensors.

General sensors (CPU, MEMORY, etc)

Disk Sensors (Disks updates)

![Screenshot 2024-11-13 at 10 13 11 am](https://github.com/user-attachments/assets/d5d37b62-1efb-490e-8783-04728064691d)

**Comment by Guruleenyc** [comment]
> @Guruleenyc @mvanlijden I have updated the code and still testing it internally but this is what I had in mind for the update intervals for Disks and other sensors.
> 
> General sensors (CPU, MEMORY, etc) in minutes
> 
> Disk Sensors (Disks updates) in hours
> 
> ![Screenshot 2024-11-13 at 10 13 11 am](https://github.com/user-attachments/assets/d5d37b62-1efb-490e-8783-04728064691d)
> 

Love it! Thank you. I look forward to it's release m

**Comment by domalab** [comment]
@Guruleenyc @mvanlijden I released a new version that should hopefully address the issue. Let me know if it works for you.

**Comment by chilman408** [comment]
Hello, wondering if this update allows the disk sensor to be disabled completely.  If the disk are spun down, it would not make sense to spin them up for a sensor update.

**Comment by domalab** [comment]
@chilman408 You are right. I'm looking at improving this by getting the integration to check the disk.cfg file for spindownDelay setting.

cat /boot/config/disk.cfg | grep -E "spindownDelay|diskSpindownDelay"

The sensor should then only check the disk for updates if its active.
