### ISSUE TITLE
HACS Link doesn't install the integration

### ISSUE THREAD

**Issue by gcordell** [domalab/ha-unraid#8]
**Describe the bug**
Using the HACS link returns 'repo not found' and nothing is installed.

**Expected behavior**
HACS integration to be installed, and have the components show up in the 'custom components' directory.  This is on HACS 2.0.1

**Screenshots**
<img width="534" alt="image" src="https://github.com/user-attachments/assets/5fec3bc6-8aa6-47f8-8d07-7d7bd0e7232e">

<img width="501" alt="image" src="https://github.com/user-attachments/assets/ac36b9b4-a68e-4897-a3f1-c949466a5fcb">

**Unraid (please complete the following information):**
 - Version 6.12.13

**Additional context**

**Comment by domalab** [comment]
@gcordell Thanks for reporting the bug.

I updated the hacs link to this repo and it's working now.

**Comment by gcordell** [comment]
thanks, works great now!

**Comment by hawaaiianmiraclecreel** [comment]
Im having the same issue + the link from github is not working either, any help would be appreciated! 
![IMG_0434](https://github.com/user-attachments/assets/eef9ad84-afc8-417c-9646-0b4717c365c3)
![IMG_0433](https://github.com/user-attachments/assets/89c9edd5-9ddc-4b76-bce2-046f42e58540)
