### ISSUE TITLE
Add Disk Temperature Attributes

### ISSUE THREAD

**Issue by jmello86** [domalab/ha-unraid#9]
First, let me say that this project is fantastic. I’ve been waiting for something like this to come along so I didn’t have to attempt to write my own! Seriously, top notch stuff, and considering the first commit is only a few weeks old, the amount of polish and attention this has gotten is incredible. Throw a donation link on here and I’ll gladly chip in to support development!

So, my feature request: can disk temperature be added as an attribute under the disk entities?

I run my homelab in my garage, and would like the ability to control automations using disk temperature, such as running my mini split air conditioner if the disks are too hot, or a script to disable spindown if they’re too cold. I know there are attributes for CPU temp, but most of the time I don’t care what temperature the CPU gets to, because it is happy anywhere between 20 and 80c, whereas disks are happiest in my experience between 35 and 45c, and should be monitored appropriately.

**Comment by domalab** [comment]
@jmello86 thanks for the compliment. 

I'm working on adding it and will update soon 😊

**Comment by domalab** [comment]
@jmello86 I’m currently traveling and won’t be able to update the code until mid-November. Once I’m back, I’ll prioritize reviewing and implementing any necessary changes.

**Comment by jmello86** [comment]
Take your time, there’s no rush!

**Comment by domalab** [comment]
@jmello86 I have added the following attributes

![Screenshot 2024-11-13 at 5 00 46 pm](https://github.com/user-attachments/assets/50d9d108-a84a-4d3d-a3ed-01ce464c0549)

**Comment by jmello86** [comment]
Sorry, I haven’t had much time for home assistant lately. I installed the update and it works great! I’ll hopefully be building out a dashboard this weekend.
Thank you so much!
Also, thanks for the donate link! 😊
